# Generated by Django 4.2.23 on 2026-06-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("launch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="waitlist",
            name="email",
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
